// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Barang struct {
  ID        string  `sql:"type:uuid" json:"id"`
  Nama      string  `sql:",unique" json:"nama"`
	Harga     float64 `json:"harga"`
	Stock     int     `json:"stock"`
	Vendor    string  `json:"vendor"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type BarangBaru struct {
	Nama   string  `json:"nama"`
	Harga  float64 `json:"harga"`
	Stock  int     `json:"stock"`
	Vendor string  `json:"vendor"`
}

type EditUser struct {
	Username string `json:"username"`
	Nama     string `json:"nama"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	Latlng   string `json:"latlng"`
}

type EditUserPassword struct {
	PasswordLama string `json:"passwordLama"`
	PasswordBaru string `json:"passwordBaru"`
}

type LoginUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenData struct {
	Token string `json:"token"`
}

type User struct {
  ID          string `sql:"type:uuid" json:"id"`
  Username    string `sql:",unique" json:"username"`
	Nama        string `json:"nama"`
	Password    string `json:"password"`
	Role        string `json:"role"`
	Email       string `json:"email"`
	Phone       string `json:"phone"`
	Address     string `json:"address"`
	Latlng      string `json:"latlng"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	LastLoginAt string `json:"lastLoginAt"`
}

type UserBaru struct {
	Username string `json:"username"`
	Nama     string `json:"nama"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Role     string `json:"role"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	Latlng   string `json:"latlng"`
}
